<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SmartActiveTools.App</RootNamespace>
    <AssemblyName>SmartActiveTools</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\SmartActiveTools.Core.csproj" />
  </ItemGroup>

</Project>
