<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SmartActiveTools.Core</RootNamespace>
    <AssemblyName>SmartActiveTools.Core</AssemblyName>
    <Version>0.21.0</Version>
  </PropertyGroup>

</Project>
